# Generated by Django 6.0.2 on 2026-02-27 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="teamuser",
            name="unique_user_team",
        ),
        migrations.AddConstraint(
            model_name="teamuser",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_user_one_team"
            ),
        ),
    ]
