# Generated by Django 6.0.2 on 2026-02-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0004_meeting_creator_alter_evaluation_task_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meeting",
            name="name",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
