# Generated by Django 6.0.2 on 2026-03-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0005_meeting_description_meeting_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="name",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
