# Generated by Django 6.0.2 on 2026-03-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0006_task_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
